import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React, { ReactNode } from 'react';
import { cookies } from 'next/headers';

import Head from 'next/head';
import MainProvider from '@providers/main-provider';

import '@src/globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

type Props = {
    children: ReactNode;
    params: {
        locale: 'ru' | 'kg';
    };
};

const RootLayout: React.FC<Props> = ({ children, params }) => {
    const cookiesStore = cookies();

    const mode = cookiesStore.get('mode');

    return (
        <html
            lang={params.locale}
            data-theme={mode?.value}
        >
            <Head>
                <link
                    href='https://fonts.cdnfonts.com/css/helvetica-neue-55'
                    rel='stylesheet'
                />
                <link
                    href='https://fonts.cdnfonts.com/css/lt-superior'
                    rel='stylesheet'
                />
            </Head>
            <body className={inter.className}>
                <MainProvider mode={(mode?.value as ModeType) || 'light'}>{children}</MainProvider>
            </body>
        </html>
    );
};

export default RootLayout;
