import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import React, { ReactNode } from 'react';

import MainProvider from '@providers/main-provider';
import Head from 'next/head';

import '@src/globals.scss';

import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Souyz KG',
    description: 'Generated by create next app',
    icons: '/images/page-icon.ico',
};

type Props = {
    children: ReactNode;
};

export const revalidate = 10;

const RootLayout: React.FC<Props> = ({ children }) => {
    const cookiesStore = cookies();

    const mode = cookiesStore.get('mode');
    const locale = cookiesStore.get('NEXT_LOCALE');

    return (
        <html
            lang={locale?.value}
            data-theme={mode?.value}
        >
            <Head>
                <link
                    href='https://fonts.cdnfonts.com/css/helvetica-neue-55'
                    rel='stylesheet'
                />
                <link
                    href='https://fonts.cdnfonts.com/css/lt-superior'
                    rel='stylesheet'
                />
            </Head>
            <body className={inter.className}>
                <NextTopLoader
                    color='#007bff'
                    height={3}
                />
                <MainProvider mode={(mode?.value as ModeType) || 'light'}>{children}</MainProvider>
            </body>
        </html>
    );
};

export default RootLayout;
